/**
 * Area 4 room interiors ("And Reconstruct Our Ruined Home", stages 6-9 and 11): the
 * deck and the machinery on it, converted from the StrategyWiki area map with
 *   python3 scripts/convert-map.py reference/maps/area4.png 0 0 450 447 5 2 0 area4
 * The rooms' walls, connecting passages, gates and markers are added in area4.ts.
 */
export const AREA4_INTERIORS: readonly string[] = [
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
  '           d d dd  d  d  d d  d  d  d dd d  d  d dd  d  dd                   d   d      d   d  d  d dd    d  d  mdd        d  d dd d  d  d dd  d d  d dd  d    d dd    dddd         ',
  '       dmmdmddmddmmmmdmdmmddmddmdmdmmddmddmddmmmmdmdmmmdmmdd    mmdmddmddmmdmdddmmmdmmmmddmmdmdmdmmddmddmddmmmmdmmmd    mmdddmmddmddmddmmmmdmdmmmdmddmdmdmmmdmddmddmmmmddmmdd       ',
  '      dmdddddddddddddddddddddddddddddddddddddddddddddddddddmd  mmddddddddddddddddddddddddddddddddddddddddddddddddddmd  mdddddddddddddddddddddddddddddddddddddddddddddddddddmd       ',
  '      ddddmdddmdddmddddddmddddddddddmmddddddddddmdddmdddddddddmdddmmddmdddmmddddddddddmdddmddddddmddddddmdddmdddmdddddddddddddmmddddddddddmdddmdddmddddddmddddddmdddmdddddddmd      ',
  '      mddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmdmmmmmmmmmmdmmmddddmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmddmdmmmmmmmmdmdmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmdmddd      ',
  '      ddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddd      ',
  '      mddmmdddddddddddddmmmmmmmmdddmmmmmmmmdddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddmmmmmdddmmddddmddddddmmddmdmdddmmmmmdddmmmmddd      ',
  '      dddmmdddddddddddddmmmmmmmmddddmmmmmmmdddddddddddddddddddmdddddddddddddddddmdddddmmdddddddddddddddddddddddddddddddddddddmddmmdmmddddddddddddddddddddmmmdddmmmmmddmdmmmddd      ',
  '     ddddmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmdmmddddddddddddddddddddddddddddddddddddmddmddddddmddddddddddmdddmdddddmdddmddmddmmddd      ',
  '      mddmmdddddddddddddmmdmmmmmmdmmmmddddddddddmmmdmmmdddddddmdddddddddddddddddddddddmmddmdddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddmmddmmddddddddddddddddddddddddddmdddddmmddmmmmddddmmmddmdddddddmmddmmddddmmmmmddmmmmmddd      ',
  '      ddddmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddmmmmmmmmddddddddddddddddddddddddddddddmmmdmmmmmmdddmdmddmmddddddmmmdmmdddmmmmmmdmmmmdmddd      ',
  '      mddmmdddddddddddddmmmmmdddddmmdddddmmddddddmmmmdddddddmdmddddddddddddddddddddddmmmddmmmddddddddddddddddddddddddddddddmmmddmmmdddddmmmddddddddddmmmddddddmmmmmmddmmmmmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmdddddddddddddddddddddddddddddddmmmddmmmmmdddmmmdmmmddddddmmddmmmdddmmmmmddmmdmmddd      ',
  '     ddddmmdddddddddddddmmdmddmdddddmdmmdmmdddddmmdmdmddddddmmmdddddddddddddddddddddddmmddmmddddddddddddddddddddddddddmddddmmmddmmmdmdddmdmdmdmddddddmmddmmmdddmmmmmdmmmdmmddd      ',
  '      mddmmdddddddddddddmmdmddmdddddmdmmdmmddddddddmddddddddmmmddddddddddddddddddddddmmmmdddddddddddddddddddddddddddddmdddddmmddmmmmmdddmmmdmmmddddddddddmmmddddddddddmdmmmddd      ',
  '      mdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmdmmmdddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '     dmddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmdmmmmdddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdddmdmddddddmdddmmmmmmmmdmddddmdddddddddddddddddddddddddddddddddddddddddddddddmmmmdmmddddddddddddddddddddddddmdddddddddddddddddddmmmmmmmdmdddddddddddddddddddddddmmmddd      ',
  '      dddmmmmmddddmmddmmmmmmmmmmmmmmmmmddmmdddddddddddddddddmmmdddddddddddddddddddddddmmddmmdddddddddddddddddddddddddddddddddmddmmdmmddmmmmmmmmmmmmmdmmmdmmddddmmmmmdddddmmddd      ',
  '      mdmmmdddddddddddmmmmmmmmmmmdmdmmmddmddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddmdddddmmddmddmdddmmmmmmmmmmmmmdmmmdmmddddmmdmddddddmmddd      ',
  '      mddmmmmmddddmdddmmmmmmmmdmmmddddddddddddddddddddddddddddddddddddddddddddddddddddmmddmdddddddddddddddddddddddddddmddddddddddddddddmmmmmmmmmmmddddmddddddddddddddddddmmddd      ',
  '      dddmmmmdmdddmmmdmmmdmmmmdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmddddddddddddddddddddddddddddddddddddddddddmmmdmmmdmmmddddddddddddddddddddddmmmddd      ',
  '      mdmmmmmmmddmmmmdmmmdmmmdmmmmddmmmddmmdddddmdmmdmddddddddmddddddddddddddddddddddmmmddmmmdddddddddddddddddddddddddmddddmmmddmmdmmddmmmdmmddmmmdddmmmdmmmdddmmmmmddddmmmddd      ',
  '      dddmmdddddddddddddddddddddddddmmmddmmdddddmdddddddddddddmddddddddddddddddddddddmmmddmmddddddddddddddddddddddddddddddddmmddmmdmmddddddddddddddddmmmdmmmdddmmmmmdddddmmddd      ',
  '     dddddmddddddddddddddddddddddddddmmdddmddddddddddmddddddddmddddddddddddddddddddddmmmmdmmddddddddddddddddddddddddddmdddddmmdddddddddddddddddddddddmmdddmmdddddddddddddmdddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddmddddmddddddddmdddddddddddddddddddddddmmddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmdmd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '     dmddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddmmdmddddddddmddddddmmmmmmmddddmmmmmmmmdddmmdmmdmmdddmmmdddmmmdddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '     dmdmmmddddddmddddddmmddmmddddddddddddddddddddmmdmddddddddmddddddmmmmmmmddddmmmmmmmmmddmmdmmdmmdddmmmdddmdmdddddddddddddddddmmdmmdddmmmddmddddddddddddddddmmmmmmdmmmmmmddd      ',
  '      mddmmmddmddmdmmdddmmmdmmddddmddmddmmmmddddddmmdmddddddddmdddddddddmmdddddddmmddmmmddddddddddddddmmmdddmmmdddddmdddddddddddmmdmmdddmmmddmmddddmdmmmmmmmddmmmmmmdmmmdmmddd      ',
  '      dddmmmdddddmddmdddmmddmmdddmmmmmmmmmmmmdddmddmdmddddddddmddddddmmdddmmmdddmmmddmmmmddmddddddmdddmmmdddmmmdddddddmdddddmmddmddmmddddmmddmddddmmmmmmmmmmmddmmmmmddmmmmmddd      ',
  '      mdmmmddddddddddddddddddddddmmmmmmmmmmmmdddddddddddddddddmddddddmmdddmmmdddmmmddmmmmddmddddddmdddmmmdddmmmdddddddmdddddddddddddddddddddddddddmmmmmmmmmmmdddddddddddmmmddd      ',
  '      mddmmdddmddmddmdddmmddddddddmmmmmmmmmmmdddddddddmmddddddmddddddmmddddmmdddmmmddmmmddddddddddddddmmmdddmmmdddddmmddddddddddmmddddddmmmdddddddmmmmmmmmmmmddmmmmmddmmmmmddd      ',
  '     dddddmmmdmddmdmmddmmmmdmmmmmdmmddmmmdmmmmmdmmmmmmdmddddddmddddddmmmmmmmmdddmmmddmmmmddmmmmmmmmmddmmmdddmdmddddddddddddddddmmmmmmdddmmmdmmmmmdmmmdmmmdmmmddmmmmmddmmdddddd      ',
  '      mddmmmmdmddmdmmddmmmmdmmmmddmmdmmmdmmmmmddmmmmmmmmddddddmddddddmmmmdmmmdddmmmmmmmmmddmmmmmmmmmddmmmdddmmmdddddmmmdddddmmddmmmmddddmmmddmmmmdmmmdmmddmmmdmmmmmmdmmmmmmdmd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      dddmmmddmdddddmdddmmddmmmdddddmmmddmmddddddddddmddddddddmddddmmmddddddddddmmdmmdmmdddmmmmmmmmddddddddddddmddddmmmddddmmmddddddddddmmmdmmmddddddmmmdmmmddmmmmmdddmmmmmddd      ',
  '      mddmmmddmddmdmmdddmmddmmmdddddmmmddmmddddddddddmmmddddddmddddmmmddddddddddmmdmmmmmmddmmmmmmmmmdddddddddmmmdddddmmddddmmmddddddddddmmmdmmmddddddmmmdmmmddmmmmmmdmmmdmmddd      ',
  '      mdddmmddddddddddddddddmmmdddddmmmddddddddmmmdddmdmddddddmddddmmddddmmdddddddddddmmdddmmmmmmmmmdddmmmmdddddddddddddddddmddddmmmddddmmmdmmmddddddmmmdmmmdddmmmdddddmdmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddmmdddmmmddddddmddddmdmddddmdddddmmdmmdmmdddddddddmmdddddmmddddmmddddddddddddmmdddmmmddddmmmdmmmddddddmmddmmmdddmmdmmddmmmmmddd      ',
  '      dddmmmddddddddddddmmddmmdddddddmmddmmdddddddmddmmmddddddmddddmmmddddddddddmmdmmdmmdddddddddmddddddddmddmmmdddddddddddmmmdddddmddddmmmdmmmddddddmmddmmmdddmmmmmdmmmmmmddd      ',
  '      mddmmmddddddddddddmdddmmdddddddmmddmddddddddddddddddddddmdddddmdddddddddddmmmdddmmddddddddddddddddddddddddddddmdddddddmdddddddddddmmmddmmddddddddddmmmddddddmmdddddmmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmmmmmmmddmmmmmmmmmddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddmdddddddddmmddmmddddddmmmddmmdddmmdmmddmmmddddddmddddmmmddmmdmmdddmmmmmdmmmddmmmmmmmmmdddmmmmmddmmddddddmdddddmmddmmdmmdddmmmdmdmddddddmmddmdmdddmmdmmddmmmmmddd      ',
  '      mdddmdddddddddddddddddmmdddddddmmdddddddddddddddddddddddmdddddddddmmmmmdddmmdddddmddddmmdmddmddddmddddddddddddddmdddddddddmmmmmdddddddddddddddddddddddddddddddddddmdmddd      ',
  '      dddmmddddddddddddddddddddddddddddddddddddmdmmdddddddddddddddddddddmddmdddddddddddddddddddddddddddmdmmdddddddddddmddddddmddmmdmmdddmdddddmddddddmdddmdddddmmdmddddmdmmddd      ',
  '      mdmdmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdddmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddmdddd      ',
  '      dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddd      ',
  '      dmdddmddmddmdmddmddmddmddmddddmddmddddddddmdmddmddmdddd dmmddmdmmddmdmmmmddmddmdmmdmmddddmddmdmmddmddddmddmdddd ddmddmddmddmddmddmddmdmddmddmddmdddddddddddddmdmmdmddddd      ',
  '       dddddddddddddddddddddddddddddddddmdmdddmmdddddddddddd   ddddddddddddddddddddddddddddddddddddddddddddddddddddd   dddddddddddddddddddddddddddddddddmmdddddddddddddddddd        ',
  '         dddddddddddddddddddddddddddddddddmdddmmddddddddddd      dddddddddddddddddddddddddddddddddddddddddddddddddd      ddddddddddddddddddddddddddddddddddddddddddddddddddd        ',
  '       dmmdmdmmmdmdmmdmdmmmdmdmmddmmmdmmmdmdddmmddmdmmdmmmdd    mmdmdmmddmmmmmmdmmddmmmmddmmdmdmdmmdmmmdmmddmmmdmmmm    mmdmdmmmmmddmmdmmmmdmdmmmdmddmmmmddddddddddmmmmmmmmd        ',
  '      dmmdddddddddddddddddddddddddddddddddddddddddddddddddddd  mmddddddddddddddddddddddddddddddddddddddddddddddddddmd  mmmdddddddddddddddddddddddddddddddddddddddddddddddddmd       ',
  '      ddddmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddd      ',
  '      mdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddmmddd      ',
  '     dmddmmdmmdmmmdddmmmmmddmmddddddmmdddmmdddmmmmmmdddmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddmmmmmddddddddddddddddmdddmdmdddmmmmmdddmmmmddd      ',
  '      mdddmddddmmdddddddddddmmmdddddddddddmdddmmmmmmddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmdmmddddmdddddddddddmddddmmdddmmdmmddddmdmddd      ',
  '      dddmmddmdmmddddmdddmddmmmdddddddmdddmddddmdmmmdmddddddddddddddmddddddddddmddddddddddddddddmddddddddddmddddddddddmddddddmddmmdmmdddmdmdmmmdddddddmmdmdddddmmmmmddmddmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmddmmddddddddddddddddddddddddddmmddd      ',
  '      mddmmdddddddddddddddddmddddddddmmddmddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddmddddddddddmmmddmmddddddmmdddmddddmmmmmddmdmmmddd      ',
  '      dddmmdddddddddddddddddmmmdddddmmmddmmddddddddddmmmddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddddddddddmmmdmmmddddddmmmdmmddddmmmmmdmmmmmmddd      ',
  '      mdmmmdddddddddddddddddddddddddmmmddmdddddmmmdddmmmddddddmddddddddddmdddddddddddddddddddddddddddmddddddddddddddddmddddmmmdddmmmddddmmmddmmddddddmmmdmddddmmmmmmdmmmmmmddd      ',
  '      mddmmdddddddddddddddddmmddddddmmdddmmdddddmmddddmdddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddmdddmmmddddmmdddmmddddddmmddmmddddmmdmdddmdmmmddd      ',
  '     ddddmmdddddddddddddddddmmmddddddmmdmmmddddddddddmmmddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmdddmmdddddmmddmmmddddddmmddmmmdddmmmmmdmmmdmmddd      ',
  '      mddmmdddddddddddddddddmmmddddddddddmmddddddddddmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddmmdddddddddddmdddmmddddddmdddmmmdddmddmdddmdmmmddd      ',
  '      mdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmddmmmdddddddddddddddddddddddddmmmddd      ',
  '     ddddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmddmmmdddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddmmmdddddddddddddddddddddddddmmmddd      ',
  '      dddmmdmmdmmmmmdddddmddmdddddddmmmddmmdddmmmmmdddddddddddmddddddddddddddddmddddddddddddddddmddddddddddmddddddddddmdddddmmddmddmmdddmmddmmmddddddmddmdmddddmmmmmdddddmmddd      ',
  '     dmddmmmmddmmdmmddddmdddmmmddddddmmddmmdddmmdmmdddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmdmmddmmdddmmddmmmddddddmdddddddddmmmmmdddddmmddd      ',
  '      mddmmdddddddddddddddddddddddddddmddmddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmmddddddddddddddmmmddddddmdmmdmmdddddddddddddmmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmddmddmmdddmmmdmmmddddddmdmmddmddddddddddddmmmddd      ',
  '      mdmmmmmmddmddmddddmmmdmmddddddmmmddmmddddmdmmdddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddmddmddddmmmddmdddddddmddmddddddmmdmdddddmmmddd      ',
  '      mddmmmmddmmdmmddddmmddmdddddddmmmddmmdddmmdmmdddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmdddddmmddddmmddmdddddddmdmmdmmdddmmmmmdddddmmddd      ',
  '      ddddmmmmddddddddddmmdddddddddddmmddmmdddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmdmmdmmmdddmmmddmmddddddddddddddddddddddddddmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmmddmdmmmdddmmmddmddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmdmddd      ',
  '     ddddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdmmddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      ddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddmdddddddddddddddddddddddddddmddddddddddmddddddmddmdmmmdddddddddddddddddddddddddddddddddddmmmddd      ',
  '     ddddmmdddddddmmmdddmmddmdddddddddmddmmdddmmmmmddmdmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdmmdmmmddddddmddddddddmmddmddddddmdddmdddmmmmddd      ',
  '      mddmmddddmmdmdmdddmmmdmmmdddddmmmddmmdddmmmmmmdmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddmddddmmmdddmddmddmmdddmmmddmddddddmmmdmddmmmmdddd      ',
  '      dddmmmmdddmdmmmdddmmmdmmmddddddmmddmmdddmmmmmmdmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmddmdmmmdddmddmmdmddddmmmddmddddddmmddmddmmmmmddd      ',
  '      ddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmdmmdmmmddddddmddmmdddmmmdmmdmmdddmmddmddmmmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddmddmmdddmddmddmmdddmmmdddddddddmmddmdmmmmmmddd      ',
  '      ddmdmmdddmmmmmddddmmmdmmmdddddmmmddmmdddmmmmdmdmmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmdddmddmmddddddmmddddddmmmddmdmmdddmdddmddmmmmmddd      ',
  '     dmddmmmmmdmmmmmddddmmddmmddddddmmmddmmdddmmmmmmdmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmdddmddmmdddmdddddmmdddmmmddmdmmdddmmddmddmdmmmddd      ',
  '      mdddmdddddmmddddddddddddddddddddddddddddmmddmdddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddmmmddmmmdddddddddmdddmddmmmdmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmddmmdmmddddmmddddddddddmddmddmmmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmddmmdmmddddmmddmdmmdddmmdddddddmmmddd      ',
  '      dddmmdddddmdmmmdddmmddmmmdddddmmmddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddmddmmmdddmmdmmdmmdddmmdddddddmmmddd      ',
  '     ddddmmmmmdmmdmdmddmmmmdmmmdddddmmmdmmmddddddddddmmmddddddmdddddmddddddddddmddddddddddddddddmddddddddddmdddddddddddddddmmmddddddddddmddmmdmmdddddddmmdddddddddddddddmmmddd      ',
  '      mddmmmmdddmdmmmdddmmmdmmmdddddmmmdmmmddddmmmddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmmdddmmmdddddddmddmmmddmmmdmmdmmdddmmmddddddmmmddd      ',
  '      mddmmmmmdmmmmmmdddmmmdmmmddddddmmddmmdddddmmdddmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmmddddmdddddmdddddmmmddmmmdmmdmmdddmmmddddddmmmddd      ',
  '     dddddmmmmdmdmmmdddmmmmdmmmddddddmmdmmmdddddmddddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddddmdddddmdddddmmddddmmdmmddddddmmdddddddmdmddd      ',
  '      mddmmmmddmmmddddddmmddmmmdddddddddmmmdddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmdddddddddddmmdmddmmdddmmmddmddddddmmmddddddmmmddd      ',
  '      mdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmdmddmddddmmmddmdmmdddmmdddddddmmmddd      ',
  '     ddddmmmdmddmmmmmddddmddmdddddddddddddmddddmdmmddmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddmmddmmmmmdddddddddmmdddmmmdmmdmmdddmmddddddddmmddd      ',
  '      mddmmmdddmmmmmmddddmddmdddddddddmdddmddddmdmmddmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddmmmmmdddmmdmddmmdddmmmdddddddddmmdddddddmmmddd      ',
  '      ddmmmmdmdmmdmmddddmmddmmddddddddmdddmdddmmdmmddddmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddmddmmdmmdddmmdmddmddddmmmddmddddddmddddddddmmmddd      ',
  '     ddddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdmdddddddddddddddddddddddddddddddddddddddddddddddddmmmdmd      ',
  '     mmdddmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddd      ',
  '      ddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd      ',
  '      dmmddmddmdddddddddddddmdddddddmddmddmddmdmddmddmddmddddddmmddmddmddmdmddmddmddmddddddddmdmddmdmmddddddddddmddmd ddmdddddmddmddddddddddmddmddmdddddddmdmmddmddmdmdddddmdd      ',
  '       ddmdddddddmdddddddddddddmddddddddddmddddddddddddddddd   ddddddddddddddddddddddmddddddddddddddddddmddddddddddd   dddddddddddmddddddddddddddddddddddddddddddddddddddddd        ',
  '        dddd dd ddmdddddddddd dddd  dddd ddddd dddd ddddddd     dddd ddddd dddd dd ddmdddddddddd ddddd ddddd ddddddd    dddd dd ddddddddddddd ddddd ddddd dddd ddddd ddddddd        ',
  '       ddddmddmmmmddddddddddmmmmmmdmmdmmddmmdmdmmmmdmmmdmmmd    dmdmddmddmdmmdmmdmddmmdddddddddmddmdmmdmmdmmmmddmmmd    dmdmdmmdmmddddddddddmdmmmdmddmmmdmmdmmddmmdmdmmmmmmd        ',
  '       mmddddddddddddddddddddddddddddddddddddddddddddddddddmd  mmddddddddddddddddddddddddddddddddddddddddddddddddddmd  dmmddddddddddddddddddddddddddddddddddddddddddddddddddd       ',
  '      mdddddddddddddddddddddddddddddddddddddddddddddddddddddddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddmdddddddddddddddddddddddddddddddddddddddddddddddddddmdd      ',
  '      ddddmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddd      ',
  '      mdmdmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '     ddddmmdddddmmmmddddmdddddddddddddddddmddddmmmmddddmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmddddddddddddddddddddddddddddddddmdddmmddd      ',
  '      mddmmddddmmmdmmdddmdddddddddddddmdddmddddmmmmdddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmdmmddddmddddmdddddmddddddddddmddddmmmdmmmddd      ',
  '      ddmmmmdmdmmmmmddddmmddmdddddddmdmddmmddddmdmmmdmmdddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmddmmmmmdddddddddddddddddddddddddddddddddddmmmddd      ',
  '     dmddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmddmmmddd      ',
  '      mddmmdddddmmddddddmmdddddddddddmddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddmmmddmmddd      ',
  '      dddmmmmddmmmmmdddmmmmdmmddddddmmmddmmddddddddddmmmddddddmddddddddddddddddmddddddddddddddmdddddddddddddddddddddddmddddmmmddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdmmmmmmdmmmdmdddmmmmdmmddddddmmmddmdddddmmmdddmmmddddddmddddddddddmddddddddddmdddddddddddddddmddddddddddmddddddmddddmmmddddmdddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      dddmmmmddmmmmmmdddmmmdmmdddddddmmddmmdddddmmdddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdmdddmmmddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      ddddmmmddmmmmdmddmmmmdmmmddddddmmdmmmdddddmmdddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddddmmddddddddddddddddddddddddddddddddddddmmdddd      ',
  '      mddmmmmmddmmmmmdddmmmdmmmddddddmddmmmddddddddddmmmddddddmdddddddddddddmddddddddddddddddddddmddddddddddddddddddmdmddddmmmddddddddddddddddddddddddddddddddddddddddddmmmdmd      ',
  '      mdmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '     ddddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdddmdddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      ddmmmddmdmmddmdddddmddmdddddddmmmddmmdddmmdmmdddddddddddmddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddmmmmmmmmdddddddddddddddddddddddddddddmmdmmdmmmmmddd      ',
  '     ddddmmddddmmdmmddddddddmmddddddmmmddmmdddmmdmmdddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmdmmmdddddddddddddddddddddddddddddmmdmmdmmmmmddd      ',
  '      mdddmmddddddddddddddddmdddddddmmmddmmdddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddmmmmmdddddddddddddddddddddddddddddddddddddmmmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddmdddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '     dmddmmmmdddmddmddddmmddmddddddddmmddmmddddmdmmdddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmddddddddddddddddddddddddddddmmmmmdmmmmmddd      ',
  '      dddmmmmmdmmdmmddddmmddddddddddmmmddmmdddmmmmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmmmmmmmddddddddddddddddddddddddddddmmmmmdmmmmmddd      ',
  '      ddddmmmmddmddmddddmmddmddddddddmmddmmddddmddddddddddddddmdddddddddddddddddddddddmddddddmddddddddddddddddddddddddmdddddmmmmmmmmdddddddddddddddddddddddddddddmmdddmmmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdmdddddddddddddddddddddddddddddddddddddddddddddddddmmmdmd      ',
  '      mdddmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      ddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmdmddd      ',
  '     ddddmmddddddddmmdddddddddddddddddddddddddmddddddmddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdddmddddmmmmmmdddmmmdmmmdddddmmmddmmdddmdmmdmdmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmmmmmmmmddddddddddddddddddddddddddddmmdmmdmmmmmddd      ',
  '      mddmmmmdddmdmmmdddmmddmmmdddddmmmddmmdddmmmmmmdmmmddddddmddddddddddmddddddddddddddddddddddddddddddddddddddddddddmddddmmmmmmmmmddddddddddddddddddddddddddddmmdmmdmmmmmddd      ',
  '     dmdddmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmdmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      ddddmmdddmmmmmddddmmmdmmmdddddmmmddmmdddmmmmmmdmmmddddddmdddddddmdddddddddmdddddddddddddddddddddddddddmdddddddddddddddmmdmdmmdddddddddddddddddddddddddddddmmdmmmmmmmmddd      ',
  '      mddmmmmddmmmmmddddmmddmmmdddddmmmddmmdddmmmmmmdmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddmmmdmdmmdddddddddddddddddddddddddddddmmdmmmmmmmmddd      ',
  '      mddmmmmdddmmddddddmmddmmmddddddmmddmmdddmmmmmddmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddmmmmmmmddd      ',
  '      dddmmddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdddmmddddddmmmdddmmddmmdddddddmmddmmdddmmmdddddddddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdmddd      ',
  '     ddddmmmmmdmmdmdmddmmmmdmmmdddddmmmdmmmdddmmmmmddmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmmddd      ',
  '      mdmmmmmdddmdmmmdddmmmdmmmdddddmmmdmmmdddmmmmdddmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmdmmmddddddmmmdmmdddddddddddddmmmddd      ',
  '      mddmmmmddmmmmmmdddmmmdmmmdddddmmdddmmdddmmddmddmdmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmddmmddddddmmmdmmddddddddddddddmmddd      ',
  '     dddddmmmmdmdmmmdddmmmmdmmmddddddmmdmdmdddmmdmmmdmmmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmddddddddddmmmddddddddddddddddmdmddd      ',
  '      mdmmmmmddmmmmddddmmmmdmmmdddddddddmmmddddddmmmdmdmddddddmdddddddddddddddddddddddddddddddddddddmddddddddddmddddddmdddddddddddddddddmmddmmmddddddmdmdmmmddddddddddddmmmddd      ',
  '      dddmmdddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddddddddmdddddddddddddddddddddddddddddddmdddddddddddddddddmmddmdmddddddmmmdmmmddddddddddddmmmddd      ',
  '     ddddmmmdmddmmmmdddddddddddddddddddddddddddmddmddddmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmddddddddddddddddddmddmmmddddddmmddmmddddddddddddddmmddd      ',
  '      mddmmmdmdmmmmmddddddddmdddddddddddddddddmmdmmddddmddddddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmddmmddddddmmmdmmdddddddddddddmmmddd      ',
  '      mddmmmdddmmdmmddddmmddmmddddddmdddddmdddmmdmmddmdmddddddmddddddddddmddddddddddddddddddddddddddddddddddddddddddddmdddddddddddddddddmmmddmdddddddmmmdmmdddddddddddddmmmddd      ',
  '      ddmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmdddmdddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmddddddmdmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmdmmmmmddd      ',
  '      mdddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmdmmdddddmdddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmdddmmmmmmmmmmmdmmmmmmmmmmdmmmmmmmmmmdmmmmmmmmmmmmmdddmd      ',
  '      ddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddddmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddd      ',
  '      dmmddmddddmmddddmdddddmddddddddddmdddddmddddmddmdmddddddddmddmddddmmdmdmmdddddmddmdmdddddmddmdmmddddmmdmddddmmddddmdddddddmmdddddmddddmdddddmddddmddddmmdddddmdmdmdddmdd      ',
  '       ddmddddmdddddmddddddddddmdddddmddddmdddddmdddddddmddd   dddddddddddddmddddddddddmdddddmddddddddddmdddddmddddd   ddddddddmddddmdddddmddddddddddmdddddmddddmdddddmdddddd       ',
  '        ddddddddddddddd dddddddddddddddddddddd dddddddddddd     ddddddddddddddddddddddddddddddddddddddddddddddddddd     ddddddddddddddddddddddddddd dddddddddddddddd ddddddd        ',
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
  '                                                                                                                                                                                    ',
];
